### ISSUE TITLE
C++11 option overwritten by C++03 option in CMake

### ISSUE THREAD

**Issue by salkinium** [ARMmbed/target-mbed-armcc#17]
This `--cpp` here overwrites the `--cpp11` option:
https://github.com/ARMmbed/target-mbed-armcc/blob/master/CMake/Platform/mbedOS-ARMCC-CXX.cmake#L17

Removing it enables the full use of C++11, e.g. lambda functions etc.

Thanks to @pan- for finding this out.

@bogdanm @bremoran @autopulated

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1666
