### ISSUE TITLE
depfile generation is probably broken

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/target-mbed-armcc#2]
It will need fixing [similar to this fix](https://github.com/ARMmbed/target-mbed-gcc/pull/1) for gcc.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-878

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1001
